// Per-format knowledge. Drives unique per-page copy and FAQs so pages are not
// one-word swaps of each other. Keyed by lowercase extension.
// lossy: true (lossy), false (lossless), null (n/a — vector/document/container).

export const FORMATS = {
  heic: { name: "HEIC", full: "High Efficiency Image Container", kind: "image", lossy: true,
    what: "the compact photo format iPhones and iPads use by default since iOS 11",
    faq: { q: "Why won't Windows or older apps open my HEIC files?", a: "HEIC is an Apple-favoured format that many Windows programs, websites and older devices still don't support. Converting to a standard format fixes that everywhere." } },
  png: { name: "PNG", full: "Portable Network Graphics", kind: "image", lossy: false,
    what: "a lossless image format that supports transparent backgrounds",
    faq: { q: "Does PNG keep transparency?", a: "Yes. PNG stores a full alpha channel, so transparent backgrounds are preserved. Formats like JPG do not support transparency and will fill it with a solid colour." } },
  jpg: { name: "JPG", full: "JPEG image", kind: "image", lossy: true,
    what: "the universally supported, compressed photo format",
    faq: { q: "Is JPG good for photos?", a: "Yes. JPG is the most widely supported photo format and compresses photographs efficiently. It is a lossy format, so it is best for final images rather than repeated re-editing." } },
  jpeg: { name: "JPEG", full: "JPEG image", kind: "image", lossy: true, what: "the universally supported, compressed photo format" },
  svg: { name: "SVG", full: "Scalable Vector Graphics", kind: "image", lossy: null,
    what: "a vector format that scales to any size without losing sharpness",
    faq: { q: "Can any image become a clean SVG?", a: "Vector tracing works best on logos, icons and flat graphics with clear edges. Detailed photographs will trace, but the result is an approximation rather than a pixel-perfect copy." } },
  webp: { name: "WEBP", full: "WebP image", kind: "image", lossy: true,
    what: "Google's modern web image format",
    faq: { q: "Why convert WEBP to something else?", a: "WEBP is efficient on the web but many desktop apps, editors and older devices still can't open it. Converting gives you a file that opens anywhere." } },
  tiff: { name: "TIFF", full: "Tagged Image File Format", kind: "image", lossy: false,
    what: "a high-resolution format used in print and professional photography",
    faq: { q: "Why are TIFF files so large?", a: "TIFF stores image data with little or no compression to preserve maximum quality, which makes files large. Converting to JPG dramatically reduces size for sharing." } },
  ico: { name: "ICO", full: "Windows Icon", kind: "image", lossy: null,
    what: "the icon format used for website favicons and Windows apps",
    faq: { q: "What size should a favicon be?", a: "A favicon commonly bundles 16×16, 32×32 and 48×48 pixel versions. PrivateRemix produces an ICO ready to drop into your website." } },
  psd: { name: "PSD", full: "Photoshop Document", kind: "image", lossy: null,
    what: "Adobe Photoshop's layered working format",
    faq: { q: "Do I need Photoshop to open a PSD?", a: "Normally yes. Converting a PSD to a standard image lets anyone view it without Adobe software — though editable layers are flattened in the process." } },
  bmp: { name: "BMP", full: "Bitmap Image", kind: "image", lossy: false,
    what: "an uncompressed legacy Windows image format",
    faq: { q: "Why convert BMP files?", a: "BMP stores images uncompressed, so files are needlessly large. Converting to JPG keeps the picture while cutting the file size significantly." } },
  gif: { name: "GIF", full: "Graphics Interchange Format", kind: "image", lossy: false,
    what: "the classic looping animation format",
    faq: { q: "Why turn a GIF into a video?", a: "GIFs are large and capped at 256 colours. MP4 video is far smaller at the same quality and plays smoothly on phones and social platforms." } },

  webm: { name: "WEBM", full: "WebM video", kind: "video", lossy: true,
    what: "an open video format built for the web",
    faq: { q: "Why won't my WEBM play in QuickTime?", a: "WEBM is designed for browsers and isn't natively supported by QuickTime or many editors. Converting to MP4 makes it play in almost any player." } },
  mov: { name: "MOV", full: "QuickTime Movie", kind: "video", lossy: true,
    what: "Apple's QuickTime video container",
    faq: { q: "What's the difference between MOV and MP4?", a: "Both are high quality, but MP4 is more universally supported across Windows, Android and web platforms. MOV is Apple's native container." } },
  mkv: { name: "MKV", full: "Matroska Video", kind: "video", lossy: true,
    what: "a flexible high-quality video container popular for HD films",
    faq: { q: "Will converting MKV to MP4 reduce quality?", a: "PrivateRemix copies the video stream where possible, so there's typically no visible quality loss — you gain compatibility with phones, TVs and editors." } },
  avi: { name: "AVI", full: "Audio Video Interleave", kind: "video", lossy: true,
    what: "an older Microsoft video format",
    faq: { q: "Why convert AVI to MP4?", a: "AVI is an older format that produces large files and struggles on modern phones and web players. MP4 is smaller and plays everywhere." } },
  mp4: { name: "MP4", full: "MPEG-4 video", kind: "video", lossy: true,
    what: "the universal video format that plays on virtually every device",
    faq: { q: "Is MP4 the best video format?", a: "For sharing and playback, yes — MP4 is supported by nearly every phone, TV, browser and editor, which is why it's the safe default." } },
  wmv: { name: "WMV", full: "Windows Media Video", kind: "video", lossy: true,
    what: "an older Windows-only video format",
    faq: { q: "Can Macs play WMV files?", a: "Not without extra software. Converting WMV to MP4 lets it play natively on Mac, iPhone and almost anything else." } },
  mts: { name: "MTS", full: "AVCHD camcorder video", kind: "video", lossy: true,
    what: "the raw AVCHD format used by many camcorders",
    faq: { q: "Why can't I edit MTS files directly?", a: "MTS/AVCHD footage isn't accepted by many editors and players. Converting to MP4 makes camcorder footage easy to edit and share." } },
  flv: { name: "FLV", full: "Flash Video", kind: "video", lossy: true,
    what: "the obsolete Flash video format",
    faq: { q: "Are FLV files still usable?", a: "Flash is discontinued and modern browsers can't play FLV. Converting to MP4 rescues old Flash videos for today's players." } },
  vob: { name: "VOB", full: "DVD Video Object", kind: "video", lossy: true,
    what: "the video container found on DVDs",
    faq: { q: "How do I play a VOB file from a DVD?", a: "VOB files rely on DVD structure and don't play well on their own. Converting to MP4 produces a single, portable video file." } },

  m4a: { name: "M4A", full: "MPEG-4 Audio", kind: "audio", lossy: true,
    what: "the AAC-based audio format Apple uses for Voice Memos and Music",
    faq: { q: "Is M4A the same as MP3?", a: "No. M4A (AAC) is Apple's format and slightly more efficient, but MP3 is more universally supported across devices and apps." } },
  wav: { name: "WAV", full: "Waveform Audio", kind: "audio", lossy: false,
    what: "an uncompressed, studio-quality audio format",
    faq: { q: "Why are WAV files so big?", a: "WAV stores audio uncompressed for maximum fidelity, so files are large. Converting to MP3 shrinks them dramatically with little audible difference." } },
  ogg: { name: "OGG", full: "Ogg Vorbis audio", kind: "audio", lossy: true,
    what: "an open audio format common in games and on the web",
    faq: { q: "Why won't my OGG file play in iTunes or on my phone?", a: "OGG isn't natively supported by many Apple and mobile apps. Converting to MP3 makes it play everywhere." } },
  flac: { name: "FLAC", full: "Free Lossless Audio Codec", kind: "audio", lossy: false,
    what: "a lossless format prized by audiophiles",
    faq: { q: "Will converting FLAC to MP3 lose quality?", a: "Technically yes — MP3 is lossy — but at a high bitrate the difference is inaudible to most listeners, and files become far smaller and more portable." } },
  mp3: { name: "MP3", full: "MP3 audio", kind: "audio", lossy: true,
    what: "the universally supported compressed audio format",
    faq: { q: "Does every device play MP3?", a: "Effectively yes. MP3 is the most widely supported audio format in the world, which is why it's the go-to for sharing." } },
  wma: { name: "WMA", full: "Windows Media Audio", kind: "audio", lossy: true,
    what: "an older Windows-only audio format",
    faq: { q: "Can iPhones play WMA files?", a: "Not natively. Converting WMA to MP3 makes your audio play on iPhone, Mac and virtually every other device." } },
  aac: { name: "AAC", full: "Advanced Audio Coding", kind: "audio", lossy: true,
    what: "the compressed audio format used by iTunes and Apple Music",
    faq: { q: "Is AAC better than MP3?", a: "AAC is slightly more efficient at the same bitrate, but MP3 wins on universal compatibility, which is why people convert to it." } },
  amr: { name: "AMR", full: "Adaptive Multi-Rate audio", kind: "audio", lossy: true,
    what: "a low-bitrate format used for old phone voice recordings",
    faq: { q: "Why convert AMR recordings?", a: "AMR is a legacy mobile voice format most modern apps can't open. Converting to MP3 makes old voice recordings playable anywhere." } },

  pdf: { name: "PDF", full: "Portable Document Format", kind: "document", lossy: null,
    what: "the universal fixed-layout document format",
    faq: { q: "Will the layout stay the same in a PDF?", a: "Yes — that's the point of PDF. It locks fonts, images and layout so the document looks identical on every device." } },
  docx: { name: "Word", full: "Microsoft Word document", kind: "document", lossy: null,
    what: "Microsoft Word's editable document format",
    faq: { q: "Can I edit the text after converting to Word?", a: "Yes. Converting to Word (.docx) produces an editable document you can change in Word, Pages or Google Docs. Complex layouts may need minor tidying." } },
  xlsx: { name: "Excel", full: "Microsoft Excel workbook", kind: "document", lossy: null,
    what: "Microsoft Excel's spreadsheet format",
    faq: { q: "How well are tables extracted into Excel?", a: "Clearly structured tables convert cleanly into rows and columns. Very complex or scanned tables may need a quick review after conversion." } },
  pptx: { name: "PowerPoint", full: "Microsoft PowerPoint presentation", kind: "document", lossy: null,
    what: "Microsoft PowerPoint's slide format",
    faq: { q: "Does each PDF page become a slide?", a: "Yes. Pages map to editable slides so you can rework a document as a presentation in PowerPoint or Keynote." } },
  epub: { name: "EPUB", full: "Electronic Publication", kind: "document", lossy: null,
    what: "the open e-book standard used by most e-readers",
    faq: { q: "What reads EPUB files?", a: "Apple Books, Google Play Books, Kobo and most e-readers open EPUB. It reflows text to fit any screen size." } },
  mobi: { name: "MOBI", full: "Mobipocket e-book", kind: "document", lossy: null,
    what: "an older Amazon Kindle e-book format",
    faq: { q: "Is MOBI still supported?", a: "Amazon has retired MOBI in favour of newer formats. Converting to EPUB keeps your books readable on modern e-readers." } },
  azw3: { name: "AZW3", full: "Kindle Format 8", kind: "document", lossy: null,
    what: "Amazon's Kindle e-book format",
    faq: { q: "Can I read AZW3 books outside a Kindle?", a: "Not easily. Converting to PDF makes a Kindle book readable on any computer, phone or tablet." } },
  rtf: { name: "RTF", full: "Rich Text Format", kind: "document", lossy: null,
    what: "a portable rich-text document format",
    faq: { q: "Why convert RTF to PDF?", a: "RTF can render slightly differently across apps. Converting to PDF locks the formatting so it looks identical for everyone you send it to." } },
  ttf: { name: "TTF", full: "TrueType Font", kind: "document", lossy: null,
    what: "a standard desktop font format",
    faq: { q: "Why convert a font to WOFF?", a: "WOFF (Web Open Font Format) is compressed and optimised for websites, loading faster than raw TTF fonts on the web." } },
  woff: { name: "WOFF", full: "Web Open Font Format", kind: "document", lossy: null, what: "the compressed font format built for the web" },
  csv: { name: "CSV", full: "Comma-Separated Values", kind: "document", lossy: null,
    what: "a plain-text format for tabular data",
    faq: { q: "Why convert CSV to Excel?", a: "CSV holds raw data with no formatting or formulas. Converting to XLSX gives you a real spreadsheet with proper columns you can style and calculate on." } },
  rar: { name: "RAR", full: "RAR archive", kind: "document", lossy: null,
    what: "a proprietary compressed archive format",
    faq: { q: "Why convert RAR to ZIP?", a: "RAR needs special software to open, while ZIP is supported natively on Mac and Windows. Converting makes the archive open with a double-click anywhere." } },
  zip: { name: "ZIP", full: "ZIP archive", kind: "document", lossy: null, what: "the universally supported compressed archive format" },
  odt: { name: "ODT", full: "OpenDocument Text", kind: "document", lossy: null,
    what: "the OpenOffice / LibreOffice document format",
    faq: { q: "Why convert ODT to PDF?", a: "ODT can shift layout between apps. Converting to PDF fixes the formatting so the document looks the same for every recipient." } },
};

// The authoritative catalog, mirrored from
// src/Sources/ProjectSwissknifeCore/Catalogs.swift (ConversionCatalog.options).
export const CATALOG = [
  ["heic", "jpg", "Convert iPhone photos to standard formats."],
  ["png", "jpg", "Reduce image file size or meet upload requirements."],
  ["svg", "png", "Convert vector graphics into standard web images."],
  ["webp", "jpg", "Convert next-gen web images for local viewing or editing."],
  ["png", "svg", "Attempt to vectorize a raster image."],
  ["jpg", "png", "Convert to a format that supports transparent backgrounds."],
  ["webp", "png", "Convert web images while preserving transparency."],
  ["tiff", "jpg", "Compress high-resolution print or photography images for web sharing."],
  ["png", "ico", "Create favicon images for website development."],
  ["heic", "png", "Export iPhone photos while preserving lossless quality and transparency."],
  ["psd", "jpg", "View Adobe Photoshop files without needing Adobe software."],
  ["bmp", "jpg", "Compress legacy Windows bitmap images into modern, lightweight files."],
  ["svg", "jpg", "Flatten scalable vectors into standard images with solid backgrounds."],
  ["webm", "mp4", "Make web videos playable on standard media players."],
  ["mov", "mp4", "Convert Apple QuickTime videos to universal formats."],
  ["mkv", "mp4", "Optimize high-quality video for mobile or TV playback."],
  ["gif", "mp4", "Turn animations into video files for social media."],
  ["avi", "mp4", "Update older video formats for modern playback."],
  ["mp4", "gif", "Create looping, silent animations from standard video clips."],
  ["wmv", "mp4", "Modernize older Windows Media Video files for universal support."],
  ["mov", "gif", "Turn iPhone screen recordings or Live Photos into shareable animations."],
  ["mts", "mp4", "Convert raw AVCHD camcorder footage into an editable format."],
  ["flv", "mp4", "Update obsolete Flash videos for modern web browsers."],
  ["mp4", "webm", "Optimize MP4s for HTML5 web embedding with smaller file sizes."],
  ["vob", "mp4", "Extract playable video files from older DVD data structures."],
  ["mp4", "mp3", "Extract audio from a video file."],
  ["m4a", "mp3", "Convert Apple audio recordings to universal formats."],
  ["wav", "mp3", "Compress lossless audio files for space."],
  ["ogg", "mp3", "Convert web or gaming audio files for standard use."],
  ["flac", "mp3", "Compress audiophile-grade tracks for mobile listening."],
  ["mp3", "wav", "Convert compressed audio into an uncompressed format for editing."],
  ["wma", "mp3", "Modernize older Windows Media Audio files."],
  ["aac", "mp3", "Convert standard iTunes or Apple Music files into universally supported tracks."],
  ["m4a", "wav", "Extract high-quality, uncompressed audio from Apple Voice Memos."],
  ["amr", "mp3", "Convert older, low-quality voice recordings from legacy mobile phones."],
  ["pdf", "docx", "Make documents editable."],
  ["pdf", "xlsx", "Extract data tables from locked documents."],
  ["jpg", "pdf", "Turn images into a document format."],
  ["epub", "pdf", "Make e-books printable or easily shareable."],
  ["docx", "pdf", "Lock formatting for document sharing."],
  ["pdf", "jpg", "Extract document pages as individual images."],
  ["pdf", "pptx", "Convert a document layout into an editable slide presentation."],
  ["mobi", "epub", "Convert older Amazon Kindle books to open-standard e-reader formats."],
  ["azw3", "pdf", "Make modern Kindle files readable on any computer or device."],
  ["rtf", "pdf", "Lock the formatting of Rich Text Files before emailing."],
  ["ttf", "woff", "Convert standard desktop fonts into Web Open Font Format for web design."],
  ["csv", "xlsx", "Convert raw comma-separated data into a formatted spreadsheet."],
  ["rar", "zip", "Convert a proprietary archive format into a universally supported compressed folder."],
  ["odt", "pdf", "Lock OpenOffice or LibreOffice documents into fixed layouts for distribution."],
];
